[package]
name = "kernel-alloc"
version = "0.1.0"
description = "Minimalistic Windows Kernel Allocator"
authors = ["not-matthias <26800596+not-matthias@users.noreply.github.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/not-matthias/kernel-alloc-rs"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.dev]
panic = "abort"

[panic.release]
pani = "abort"